name: Push - Create & Tag Protobuf - Go

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
          check-latest: false
          cache: true

      - name: Install Protoc
        run: |
          PROTOC_VERSION=25.1
          PROTOC_ZIP=protoc-${PROTOC_VERSION}-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          protoc --version

      - name: Generate Go Source
        shell: bash
        run: |
          make pipeline-build
      - name: Update go.mod
        run: |
          go mod tidy
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(protobuf-go) : Auto-generated by Github Action"
          tagging_message: ${{ steps.tag_version.outputs.new_tag }}
          file_pattern: "protogen/*"
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
